version: "3.9"

services:
  foodies-api:
    image: kayceecode/foodies-api
    environment:
      - JWT_KEY_SECRET_FILE=/run/secrets/jwt-secret
      - DB_CONNECTION_FILE=/run/secrets/db-connection
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:8080
    ports:
      - "8082:8080"   
    depends_on:
      - foodies-api-db

    secrets:
      - postgres-passwd
      - jwt-secret
      - db-connection
    restart: always

  foodies-api-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
      POSTGRES_USER: postgres
      POSTGRES_DB: foodiesapidb
    secrets:
      - postgres-passwd
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5430:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  db-data:

secrets:
  postgres-passwd:
    file: ./secrets/postgres-passwd.txt
  jwt-secret:
    file: ./secrets/jwt-secret.txt
  db-connection:
    file: ./secrets/db-connection.txt