services:
  foodies-api:
    image: kayceecode/foodies-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DB_HOST=foodies-api-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_NAME=foodiesapidb
    ports:
      - "8082:8080"
    depends_on:
      - foodies-api-db
    secrets:
      - postgres-passwd

  foodies-api-db:
    image: postgres
    container_name: foodies-api-db-container
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
      POSTGRES_USER: postgres
      POSTGRES_DB: foodiesapidb
    secrets:
      - postgres-passwd
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5430:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s

volumes:
  db-data:
secrets:
  postgres-passwd:
    external: true