#      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=app_db;Port=5432;Database=FoodiesApiDb; IntegratedSecurity=true;Pooling=true;
services: 
  db:
    image: postgres
    restart: always
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
    secrets:
      - postgres-passwd
    volumes:
      - db-data:/var/lib/postgresql/data  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data: 

secrets:
  postgres-passwd:
    file: ./postgres_passwd.txt