apiVersion: v1
kind: Service
metadata:
  name: foodiesapinp-srv
spec:
  type: NodePort
  selector:
    app: foodiesapi
  ports:
    - name: foodiesapi
      protocol: TCP
      port: 8080
      targetPort: 8080